//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01.TestingPerformanceWithWithoutInclude
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LodID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<decimal> OldSum { get; set; }
        public Nullable<decimal> NewSum { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
