-- MySQL Script generated by MySQL Workbench
-- 08/28/14 13:24:11
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema booksDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `booksDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `booksDB` ;

-- -----------------------------------------------------
-- Table `booksDB`.`Authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booksDB`.`Authors` (
  `AuthorId` INT NOT NULL AUTO_INCREMENT,
  `AuthorName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`AuthorId`),
  UNIQUE INDEX `AuthorId_UNIQUE` (`AuthorId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksDB`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booksDB`.`Books` (
  `BookId` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(50) NOT NULL,
  `PublishDate` DATETIME NULL,
  `ISBN` INT NULL,
  `AuthorId` INT NOT NULL,
  PRIMARY KEY (`BookId`, `AuthorId`),
  UNIQUE INDEX `BookId_UNIQUE` (`BookId` ASC),
  UNIQUE INDEX `ISBN_UNIQUE` (`ISBN` ASC),
  INDEX `fk_Books_Authors_idx` (`AuthorId` ASC),
  CONSTRAINT `fk_Books_Authors`
    FOREIGN KEY (`AuthorId`)
    REFERENCES `booksDB`.`Authors` (`AuthorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
